config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :destinations

  get 'about'=>'welcome#about'

  get 'contact' => 'welcome#contact'

  root 'welcome#index'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
    @countries = []
    
    @destinations.each do |destination| 
      @countries.push(destination.country)
    end
    
    @countries = @countries.uniq.sort

    # if params[:country] != nil
    #   @destinations = Destination.where(country: params[:country].titleize)
    # else
    #   @destinations = Destination.all
    # end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.create(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homeland = 'Italy'
  	@countries = ["Sweden", "Iceland", "Germany"]
  	@images = ["blue_lagoon.jpg", "iceland_northernlights.jpg", "iceland_summer.jpg", "iceland_waterfall.jpg"]
  end

  def about
  	@color = params[:color]
  	@size = params[:size]
  end

  def contact
  	@united_states ={"capital_city"=>"Washington D.C.", "favorite_city" => "Los Angeles", "favorite_state"=> "California", "flag_colors"=> ["red","white","blue"]}
  end 
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for @destination do |f| %>
   
    <% if @destination.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination  from being saved:</h2>

       <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
       </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :city %><br>
      <%= f.text_field :city, class: "form-control"%>
    </div>

    <div class="field form-group">
      <%= f.label :country %><br>
      <%= f.text_field :country, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
  

    <div class="actions" >
      <%= f.submit class: "btn btn-primary" %>
    </div>

    <div>
       <%= f.file_field :avatar %>
    </div>


<% end %>

app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1>Listing destinations</h1>

<ul class="nav nav-pills" role="tablist">
  <% @countries.each do |country| %> 
    <li><%= link_to "#{country}", controller: "destinations", country: "#{country}" %></li> 
  <%end%>
</ul>

  <div class="row">   
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
          <h2><%= destination.city %></h2>
          <h3><%= destination.country %></h3>
    
        <p><%= destination.description %></p>
        <p><% if destination.avatar_file_name!=nil%>
          <%=image_tag destination.avatar.url (:medium) %></p>
           <%end%> 
        <div class="btn-group">
          <%= link_to 'Show', destination, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-default" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>

        </div>
       </div>     
      </div>
    <% end %>
  </div>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<!-- <p id="notice" class="alert alert-success" ><%= notice %></p> -->

<p>
  <strong>City:</strong>
  <%= @destination.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @destination.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @destination.description %>
</p>

<%= image_tag @destination.avatar.url(:medium) %>
 
<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/show_japan.html.erb
<h1>Japan!</h1>



<% @japan.each do |item| %>
	<h1><%= item.city %></h1>
	<p><%= item.description %></p>
<%end%>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <link rel="stylesheet" href="assets/stylesheets/bootstrap.css">
  <!--  <link rel="stylesheet" href="assets/stylesheets/override.css"> -->
  <script src="assets/javascripts/bootstrap.js"></script>

<%= csrf_meta_tags %>
</head>


<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <!-- <a class="navbar-brand" href="#">Lizzy is boss</a>-->
      <%= link_to "Lizzy is Boss", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "About", about_path %></li>
        <li><%=link_to "Destinations", destinations_path %></li>
        <li><%=link_to "Blog", blogs_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class = "container">
<%= yield %>
</div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>This is my color page</h1>
<p>Can you figure out what my favorite color is?</p>

<body bgcolor = <%= @color %>>
<p>My favorite color is <%= @color %> and my show size is <%= @size %> 
<br>	
<% if @size.to_i > 12 %>
<%= "Your feet are huge!" %>
<% else %>
<%= "Your feet are normal sized, I guess" %>
<% end %>
</p>

</body>

app/views/welcome/contact.html.erb
<h1>This is my Contact page</h1>
<p>WELCOME!!</p>

<p>
 <table style="width:100%">
  <tr>
  	<% @united_states.each do |key, value| %>
    <td><%= key %></td>
    <%end%>
  </tr>
  <tr>
    <% @united_states.each do |key, value| %>
    <% if color.kind_of?(Array) == false %>
    	<td><%=value%></td>
    	<% else %>
    	<tdvalue.each do |color|
    <%= color %></td>
    <%end%>
    <%end%>
  </tr>
</table> 




</p>	

app/views/welcome/index.html.erb
<h1>Lizzy Travels</h1>
<p>Welcome to Lizzy's boss website. It will include lots of stuff about my travels.</p>

<%= @homeland %>
<br>
<ul>
<% @countries.each do |country| %>
	<li><%= country %></li>
<% end %>
</ul>

<br>

<br>	
<% @images.each do |image| %>
	<%= image_tag image, width: "47%", height: "400px" %>
<% end %>